"use client"

import { useState, type FormEvent } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { Activity, ArrowRight, Bird, Birdhouse, Binoculars, Check, ChevronRight, ClipboardList, Download, Egg, MapPin, Plus, Search, Trash2, TrendingUp, Wrench } from "lucide-react"
import { useApp } from "@/components/app/app-provider"
import { Badge, Card, EmptyState, fieldClass } from "@/components/app/ui"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import type { AppSettings, ColonyStatus, ObservationType } from "@/lib/types"

const fmt = (date: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`))
const statusTone = (status: ColonyStatus) => status === "Active" ? "green" : status === "Needs attention" ? "amber" : "neutral"

export function DashboardScreen() {
  const { colonies, observations } = useApp()
  const totals = colonies.reduce((sum, colony) => ({ occupied: sum.occupied + colony.occupied, compartments: sum.compartments + colony.compartments, eggs: sum.eggs + colony.eggs, nestlings: sum.nestlings + colony.nestlings }), { occupied: 0, compartments: 0, eggs: 0, nestlings: 0 })
  const recent = [...observations].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 4)
  const occupancy = totals.compartments ? Math.round(totals.occupied / totals.compartments * 100) : 0
  return <div className="space-y-8">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-[#527a66]">2026 breeding season</p><h2 className="mt-1 text-3xl font-bold tracking-tight">Good morning, Alex</h2><p className="text-muted-foreground mt-2">Here’s how your purple martin colonies are doing.</p></div><Button asChild variant="outline"><Link href="/dashboard/colonies/new"><Plus />Add colony</Link></Button></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {[{ label: "Active colonies", value: colonies.filter(c => c.status !== "Inactive").length, detail: `${colonies.length} total sites`, icon: MapPin }, { label: "Occupancy", value: `${occupancy}%`, detail: `${totals.occupied} of ${totals.compartments} compartments`, icon: Activity }, { label: "Eggs", value: totals.eggs, detail: "Across active nests", icon: Egg }, { label: "Nestlings", value: totals.nestlings, detail: "Currently monitored", icon: Bird }].map(({ label, value, detail, icon: Icon }) => <Card key={label} className="p-5"><div className="flex items-start justify-between"><div><p className="text-muted-foreground text-sm">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight">{value}</p></div><div className="flex size-10 items-center justify-center rounded-xl bg-[#edf2e5] text-[#38614f]"><Icon className="size-5" /></div></div><p className="text-muted-foreground mt-3 text-xs">{detail}</p></Card>)}
    </section>
    <section className="grid gap-6 xl:grid-cols-[1.4fr_.8fr]">
      <Card><div className="flex items-center justify-between border-b p-5"><div><h3 className="font-semibold">Recent observations</h3><p className="text-muted-foreground text-sm">Latest activity across your sites</p></div><Button asChild variant="ghost" size="sm"><Link href="/dashboard/observations">View all <ArrowRight /></Link></Button></div><div className="divide-y">{recent.map(obs => { const colony = colonies.find(c => c.id === obs.colonyId); return <Link href="/dashboard/observations" key={obs.id} className="flex items-center gap-4 p-5 transition-colors hover:bg-muted/40"><div className="flex size-10 shrink-0 items-center justify-center rounded-full bg-sky-50 text-sky-700"><Binoculars className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{colony?.name ?? "Unknown colony"}</p><p className="text-muted-foreground truncate text-xs">{obs.type} · {obs.notes}</p></div><div className="text-right"><p className="text-sm">{fmt(obs.date)}</p><p className="text-muted-foreground text-xs">{obs.time}</p></div></Link>})}</div></Card>
      <Card className="overflow-hidden"><div className="bg-[#17352d] p-6 text-white"><div className="flex items-center justify-between"><div><p className="text-sm text-white/60">Season progress</p><p className="mt-1 text-2xl font-bold">Peak nesting</p></div><TrendingUp className="size-7 text-[#d9f06d]" /></div><div className="mt-6 h-2 rounded-full bg-white/15"><div className="h-full w-[68%] rounded-full bg-[#d9f06d]" /></div><div className="mt-2 flex justify-between text-xs text-white/55"><span>Arrival</span><span>Fledging</span></div></div><div className="space-y-4 p-5"><h3 className="font-semibold">Needs attention</h3>{colonies.filter(c => c.status === "Needs attention").map(c => <Link key={c.id} href="/dashboard/colonies" className="flex items-center gap-3 rounded-xl bg-amber-50 p-3"><Wrench className="size-4 text-amber-700" /><div className="flex-1"><p className="text-sm font-medium">{c.name}</p><p className="text-xs text-amber-800/70">Maintenance noted</p></div><ChevronRight className="size-4" /></Link>)}<div className="flex items-center gap-3 rounded-xl bg-emerald-50 p-3"><Check className="size-4 text-emerald-700" /><p className="text-sm">All other colonies are on schedule</p></div></div></Card>
    </section>
  </div>
}

export function ColoniesScreen() {
  const { colonies, observations, removeColony } = useApp(); const [query, setQuery] = useState(""); const [status, setStatus] = useState("All")
  const shown = colonies.filter(c => (status === "All" || c.status === status) && `${c.name} ${c.location}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-3xl font-bold tracking-tight">Colonies</h2><p className="text-muted-foreground mt-2">Monitor housing, occupancy, and nest health at every site.</p></div><Button asChild className="bg-[#17352d]"><Link href="/dashboard/colonies/new"><Plus />Add colony</Link></Button></div><Card className="p-3"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="text-muted-foreground absolute left-3 top-2.5 size-4" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search colonies or locations…" className="pl-9 shadow-none" /></div><select className="h-9 rounded-md border bg-white px-3 text-sm" value={status} onChange={e => setStatus(e.target.value)}><option>All</option><option>Active</option><option>Needs attention</option><option>Inactive</option></select></div></Card>{shown.length === 0 ? <EmptyState icon={<MapPin />} title="No colonies found" description="Try another filter or add your first monitoring site." action={<Button asChild><Link href="/dashboard/colonies/new">Add colony</Link></Button>} /> : <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{shown.map(colony => { const count = observations.filter(o => o.colonyId === colony.id).length; const pct = Math.round(colony.occupied / colony.compartments * 100); return <Card key={colony.id} className="overflow-hidden"><div className="h-2 bg-[#527a66]" /><div className="p-5"><div className="flex items-start justify-between gap-3"><div><Badge tone={statusTone(colony.status)}>{colony.status}</Badge><h3 className="mt-3 text-lg font-semibold">{colony.name}</h3><p className="text-muted-foreground mt-1 flex items-start gap-1 text-sm"><MapPin className="mt-0.5 size-3.5 shrink-0" />{colony.location}</p></div><Button variant="ghost" size="icon-sm" aria-label={`Delete ${colony.name}`} onClick={() => confirm(`Delete ${colony.name} and its observations?`) && removeColony(colony.id)}><Trash2 className="text-muted-foreground" /></Button></div><div className="mt-5 grid grid-cols-3 gap-2 rounded-xl bg-muted/60 p-3 text-center"><div><p className="font-semibold">{pct}%</p><p className="text-muted-foreground text-xs">Occupied</p></div><div><p className="font-semibold">{colony.eggs}</p><p className="text-muted-foreground text-xs">Eggs</p></div><div><p className="font-semibold">{colony.nestlings}</p><p className="text-muted-foreground text-xs">Nestlings</p></div></div><div className="text-muted-foreground mt-4 flex items-center justify-between text-xs"><span>Checked {fmt(colony.lastChecked)}</span><span>{count} records</span></div><p className="mt-4 line-clamp-2 text-sm leading-relaxed">{colony.notes}</p><Button asChild variant="outline" className="mt-5 w-full"><Link href={`/dashboard/observations/new?colony=${colony.id}`}>Log site visit <ChevronRight /></Link></Button></div></Card>})}</div>}</div>
}

export function ObservationsScreen() {
  const { observations, colonies, removeObservation } = useApp(); const [query, setQuery] = useState("")
  const shown = [...observations].sort((a,b) => `${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)).filter(o => { const c = colonies.find(x => x.id === o.colonyId); return `${c?.name} ${o.type} ${o.notes}`.toLowerCase().includes(query.toLowerCase()) })
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-3xl font-bold tracking-tight">Field observations</h2><p className="text-muted-foreground mt-2">A complete journal of visits, nest checks, and maintenance.</p></div><Button asChild className="bg-[#17352d]"><Link href="/dashboard/observations/new"><Plus />Log observation</Link></Button></div><div className="relative max-w-md"><Search className="text-muted-foreground absolute left-3 top-3 size-4" /><Input className="h-10 bg-white pl-9" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search field notes…" /></div>{shown.length ? <Card className="overflow-hidden"><div className="divide-y">{shown.map(o => { const c = colonies.find(x => x.id === o.colonyId); return <article key={o.id} className="group p-5 hover:bg-muted/25"><div className="flex gap-4"><div className="hidden w-16 shrink-0 text-center sm:block"><p className="text-2xl font-bold">{new Date(`${o.date}T12:00:00`).getDate()}</p><p className="text-muted-foreground text-xs uppercase">{new Intl.DateTimeFormat("en", { month:"short" }).format(new Date(`${o.date}T12:00:00`))}</p></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge tone="blue">{o.type}</Badge><p className="font-semibold">{c?.name}</p><span className="text-muted-foreground text-xs sm:hidden">{fmt(o.date)}</span></div><p className="text-muted-foreground mt-2 text-sm leading-relaxed">{o.notes}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs"><span><strong>{o.adults}</strong> adults</span><span><strong>{o.eggs}</strong> eggs</span><span><strong>{o.nestlings}</strong> nestlings</span><span><strong>{o.fledglings}</strong> fledglings</span><span className="text-muted-foreground">{o.weather}</span></div></div><Button variant="ghost" size="icon-sm" aria-label="Delete observation" className="opacity-50 group-hover:opacity-100" onClick={() => confirm("Delete this observation?") && removeObservation(o.id)}><Trash2 /></Button></div></article>})}</div></Card> : <EmptyState icon={<Binoculars />} title="No observations found" description="Your matching field records will appear here." />}</div>
}

export function CalendarScreen() {
  const { observations, colonies } = useApp(); const [monthOffset, setMonthOffset] = useState(0); const base = new Date(2026, 6 + monthOffset, 1); const year = base.getFullYear(), month = base.getMonth(); const days = new Date(year, month + 1, 0).getDate(), start = new Date(year, month, 1).getDay();
  const cells = Array.from({ length: 42 }, (_, i) => { const day = i - start + 1; return day > 0 && day <= days ? day : null })
  return <div className="space-y-6"><div><h2 className="text-3xl font-bold tracking-tight">Season calendar</h2><p className="text-muted-foreground mt-2">Review monitoring activity and plan your next checks.</p></div><Card className="overflow-hidden"><div className="flex items-center justify-between border-b p-5"><Button variant="outline" size="sm" onClick={() => setMonthOffset(v => v-1)}>Previous</Button><h3 className="font-semibold">{new Intl.DateTimeFormat("en", { month:"long", year:"numeric" }).format(base)}</h3><Button variant="outline" size="sm" onClick={() => setMonthOffset(v => v+1)}>Next</Button></div><div className="grid grid-cols-7 border-b bg-muted/40">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d => <div key={d} className="p-2 text-center text-xs font-medium text-muted-foreground">{d}</div>)}</div><div className="grid grid-cols-7">{cells.map((day,i) => { const date = day ? `${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}` : ""; const events = observations.filter(o => o.date === date); return <div key={i} className="min-h-24 border-b border-r p-2 md:min-h-28"><span className="text-xs font-medium">{day}</span>{events.map(e => <div key={e.id} className="mt-1 truncate rounded bg-[#dfead5] px-1.5 py-1 text-[10px] text-[#254c3d]" title={colonies.find(c => c.id === e.colonyId)?.name}>{e.type}</div>)}</div> })}</div></Card></div>
}

export function ReportsScreen() {
  const { colonies, observations } = useApp(); const max = Math.max(...colonies.map(c => c.occupied), 1); const totalFledged = observations.reduce((n,o) => n + o.fledglings, 0)
  const download = () => { const rows = [["Date","Colony","Type","Adults","Eggs","Nestlings","Fledglings","Weather","Notes"], ...observations.map(o => [o.date, colonies.find(c=>c.id===o.colonyId)?.name ?? "", o.type, o.adults, o.eggs, o.nestlings, o.fledglings, o.weather, o.notes])]; const csv = rows.map(row => row.map(v => `"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"); const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"})); a.download="purple-martin-observations.csv"; a.click(); URL.revokeObjectURL(a.href) }
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-3xl font-bold tracking-tight">Season reports</h2><p className="text-muted-foreground mt-2">Understand occupancy and reproductive activity across your sites.</p></div><Button variant="outline" onClick={download}><Download />Export CSV</Button></div><div className="grid gap-4 sm:grid-cols-3">{[{label:"Field visits",value:observations.length,icon:ClipboardList},{label:"Total fledgling counts",value:totalFledged,icon:Bird},{label:"Colony sites",value:colonies.length,icon:MapPin}].map(({label,value,icon:Icon})=><Card key={label} className="p-5"><Icon className="size-5 text-[#527a66]"/><p className="mt-4 text-3xl font-bold">{value}</p><p className="text-muted-foreground text-sm">{label}</p></Card>)}</div><div className="grid gap-6 lg:grid-cols-2"><Card className="p-6"><h3 className="font-semibold">Occupied compartments by colony</h3><p className="text-muted-foreground mt-1 text-sm">Current reported occupancy</p><div className="mt-8 space-y-5">{colonies.map(c => <div key={c.id}><div className="mb-2 flex justify-between text-sm"><span>{c.name}</span><strong>{c.occupied}/{c.compartments}</strong></div><div className="h-3 rounded-full bg-muted"><div className="h-full rounded-full bg-[#527a66]" style={{width:`${c.occupied/max*100}%`}} /></div></div>)}</div></Card><Card className="p-6"><h3 className="font-semibold">Current nest stage</h3><p className="text-muted-foreground mt-1 text-sm">Eggs and nestlings by site</p><div className="mt-6 space-y-4">{colonies.map(c => <div key={c.id} className="rounded-xl border p-4"><div className="flex justify-between"><span className="text-sm font-medium">{c.name}</span><span className="text-xs text-muted-foreground">{c.eggs+c.nestlings} total</span></div><div className="mt-3 flex h-3 overflow-hidden rounded-full bg-muted"><div className="bg-amber-400" style={{width:`${c.eggs/(c.eggs+c.nestlings||1)*100}%`}}/><div className="bg-sky-500" style={{width:`${c.nestlings/(c.eggs+c.nestlings||1)*100}%`}}/></div><div className="mt-2 flex gap-4 text-xs"><span><i className="mr-1 inline-block size-2 rounded-full bg-amber-400"/>{c.eggs} eggs</span><span><i className="mr-1 inline-block size-2 rounded-full bg-sky-500"/>{c.nestlings} nestlings</span></div></div>)}</div></Card></div></div>
}

export function SettingsScreen() {
  const { settings, updateSettings, resetDemo } = useApp(); const [form,setForm]=useState<AppSettings>(settings); const [saved,setSaved]=useState(false)
  const submit=(e:FormEvent)=>{e.preventDefault();updateSettings(form);setSaved(true);setTimeout(()=>setSaved(false),2000)}
  return <div className="mx-auto max-w-3xl space-y-6"><div><h2 className="text-3xl font-bold tracking-tight">Settings</h2><p className="text-muted-foreground mt-2">Manage your observer profile and monitoring preferences.</p></div><form onSubmit={submit} className="space-y-6"><Card className="p-6"><h3 className="font-semibold">Observer profile</h3><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Full name<Input className="mt-1.5" value={form.observerName} onChange={e=>setForm({...form,observerName:e.target.value})}/></label><label className="text-sm font-medium">Email<Input type="email" className="mt-1.5" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div></Card><Card className="p-6"><h3 className="font-semibold">Season preferences</h3><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Season start<Input type="date" className="mt-1.5" value={form.seasonStart} onChange={e=>setForm({...form,seasonStart:e.target.value})}/></label><label className="text-sm font-medium">Measurement units<select className={fieldClass} value={form.units} onChange={e=>setForm({...form,units:e.target.value as AppSettings["units"]})}><option value="imperial">Imperial</option><option value="metric">Metric</option></select></label></div><div className="mt-6 space-y-4">{[["weeklyReminder","Weekly monitoring reminder"],["arrivalAlerts","Arrival and fledging alerts"]] .map(([key,label]) => <label key={key} className="flex items-center justify-between gap-4 rounded-xl border p-4 text-sm font-medium"><span>{label}</span><input type="checkbox" className="size-4 accent-[#38614f]" checked={form[key as "weeklyReminder"|"arrivalAlerts"] as boolean} onChange={e=>setForm({...form,[key]:e.target.checked})}/></label>)}</div></Card><div className="flex items-center justify-between"><Button type="button" variant="destructive" onClick={()=>confirm("Restore all sample colonies and observations?")&&resetDemo()}>Reset demo data</Button><Button type="submit" className="bg-[#17352d]">{saved?<><Check/>Saved</>:"Save changes"}</Button></div></form></div>
}

export function ColonyForm() {
  const { addColony }=useApp(); const router=useRouter(); const today=new Date().toISOString().slice(0,10)
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);addColony({name:String(f.get("name")),location:String(f.get("location")),latitude:Number(f.get("latitude")),longitude:Number(f.get("longitude")),compartments:Number(f.get("compartments")),occupied:Number(f.get("occupied")),eggs:Number(f.get("eggs")),nestlings:Number(f.get("nestlings")),status:String(f.get("status")) as ColonyStatus,lastChecked:String(f.get("lastChecked")),notes:String(f.get("notes"))});router.push("/dashboard/colonies")}
  return <div className="mx-auto max-w-3xl"><div className="mb-6"><h2 className="text-3xl font-bold tracking-tight">Add a colony</h2><p className="text-muted-foreground mt-2">Create a monitoring site and record its current housing status.</p></div><form onSubmit={submit}><Card className="space-y-6 p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Colony name<input required name="name" placeholder="e.g. Lakeside Gourd Rack" className={fieldClass}/></label><label className="text-sm font-medium sm:col-span-2">Location<input required name="location" placeholder="Park, town, state" className={fieldClass}/></label><label className="text-sm font-medium">Latitude<input required name="latitude" type="number" step="any" className={fieldClass}/></label><label className="text-sm font-medium">Longitude<input required name="longitude" type="number" step="any" className={fieldClass}/></label><label className="text-sm font-medium">Compartments<input required name="compartments" type="number" min="1" defaultValue="12" className={fieldClass}/></label><label className="text-sm font-medium">Occupied<input required name="occupied" type="number" min="0" defaultValue="0" className={fieldClass}/></label><label className="text-sm font-medium">Eggs<input required name="eggs" type="number" min="0" defaultValue="0" className={fieldClass}/></label><label className="text-sm font-medium">Nestlings<input required name="nestlings" type="number" min="0" defaultValue="0" className={fieldClass}/></label><label className="text-sm font-medium">Status<select name="status" className={fieldClass}><option>Active</option><option>Needs attention</option><option>Inactive</option></select></label><label className="text-sm font-medium">Last checked<input name="lastChecked" type="date" defaultValue={today} className={fieldClass}/></label><label className="text-sm font-medium sm:col-span-2">Site notes<textarea name="notes" rows={4} placeholder="Access details, maintenance notes, site contacts…" className={`${fieldClass} h-auto py-3`}/></label></div><div className="flex justify-end gap-3 border-t pt-5"><Button asChild variant="outline"><Link href="/dashboard/colonies">Cancel</Link></Button><Button type="submit" className="bg-[#17352d]">Create colony</Button></div></Card></form></div>
}

export function ObservationForm({ defaultColony }: { defaultColony?: string }) {
  const { colonies, addObservation }=useApp(); const router=useRouter(); const now=new Date(); const today=now.toISOString().slice(0,10); const time=now.toTimeString().slice(0,5)
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);addObservation({colonyId:String(f.get("colonyId")),date:String(f.get("date")),time:String(f.get("time")),type:String(f.get("type")) as ObservationType,adults:Number(f.get("adults")),eggs:Number(f.get("eggs")),nestlings:Number(f.get("nestlings")),fledglings:Number(f.get("fledglings")),weather:String(f.get("weather")),notes:String(f.get("notes"))});router.push("/dashboard/observations")}
  return <div className="mx-auto max-w-3xl"><div className="mb-6"><h2 className="text-3xl font-bold tracking-tight">Log an observation</h2><p className="text-muted-foreground mt-2">Capture field conditions and the latest colony counts.</p></div>{colonies.length===0?<EmptyState icon={<Birdhouse/>} title="Add a colony first" description="Observations must be attached to a monitoring site." action={<Button asChild><Link href="/dashboard/colonies/new">Add colony</Link></Button>}/>:<form onSubmit={submit}><Card className="space-y-6 p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Colony<select required name="colonyId" defaultValue={defaultColony} className={fieldClass}><option value="" disabled>Select a colony</option>{colonies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm font-medium">Date<input required name="date" type="date" defaultValue={today} className={fieldClass}/></label><label className="text-sm font-medium">Time<input required name="time" type="time" defaultValue={time} className={fieldClass}/></label><label className="text-sm font-medium">Visit type<select name="type" className={fieldClass}><option>Routine check</option><option>Nest check</option><option>Arrival</option><option>Fledging</option><option>Maintenance</option></select></label><label className="text-sm font-medium">Weather<input name="weather" placeholder="Clear, 75°F" className={fieldClass}/></label>{["adults","eggs","nestlings","fledglings"].map(label=><label key={label} className="text-sm font-medium capitalize">{label}<input required name={label} type="number" min="0" defaultValue="0" className={fieldClass}/></label>)}<label className="text-sm font-medium sm:col-span-2">Field notes<textarea required name="notes" rows={5} placeholder="Behavior, nest condition, maintenance, predator activity…" className={`${fieldClass} h-auto py-3`}/></label></div><div className="flex justify-end gap-3 border-t pt-5"><Button asChild variant="outline"><Link href="/dashboard/observations">Cancel</Link></Button><Button type="submit" className="bg-[#17352d]">Save observation</Button></div></Card></form>}</div>
}
